DECLARE VARIABLE JIDLO_OD_0 BIGINT;
DECLARE VARIABLE JIDLO_DO_0 BIGINT;
DECLARE VARIABLE OBJEDNAVKY_PREDEM_DNI_0 BIGINT;
DECLARE VARIABLE T_DO_OBJEDNAVKY_0 Time;

DECLARE VARIABLE VIKENDOO BIGINT;   --tyden nakdy objednavka
DECLARE VARIABLE VIKENDDNES BIGINT;  -- tyden kdy objednávám
DECLARE VARIABLE D_OBJEDNAVANI_0 DATE ;  -- den datum kdy objednáváme
DECLARE VARIABLE T_OBJEDNAVANI_0 TIME ;  -- čas kdy objednáváme
DECLARE VARIABLE MOZNOST_BURZA_VLOZIT_0 CUBOOLEAN; --zdali je povolená burza ve zvolené jídelně
DECLARE VARIABLE DEN_0 BIGINT;  --den v týdnu kdy obhednávám - pro víkendy

BEGIN
     :OBJEDNAVKA0 = 'N';
     :MAM_VBURZE = 'N';
     :VYDANO = 'N';
  :D_OBJEDNAVANI_0 = CAST(D_OBJEDNAVANI_ AS DATE);
  :T_OBJEDNAVANI_0 = CAST(D_OBJEDNAVANI_ AS TIME);
  MOZNOST_BURZA_VLOZIT ='N';
  MAX_POCET_OBJ_JIDEL = 0;
  SELECT FIRST 1 DISTINCT JIDLO_OD, JIDLO_DO, Lfd_Ji_TYP, OBJEDNAVKY_PREDEM_DNI,  T_DO_OBJEDNAVKY , EXTRACT(WEEK FROM :D_OBJEDNAVANI_0),EXTRACT(WEEK FROM :DATUM_)
     ,MAX_POCET_OBJ_JIDEL
  FROM TJIDELAK_DEN_FAZE JDF 
    --WHERE (JDF.LFD_JI_TYP = :LFD_JI_TYP_)  --AND (JDF.LFD_JI_TYP_CAST=1)
    --     AND  (JDF.LFD_JI_TYP_CAST = :LFD_JI_TYP_CAST_)  
    WHERE (JDF.LFD_JIDELNA=:LFD_JIDELNA_) AND (JDF.AKTIVNI = 'A')
    INTO :JIDLO_OD_0 , :JIDLO_DO_0 , :LFD_JI_TYP_ , :OBJEDNAVKY_PREDEM_DNI_0,  :T_DO_OBJEDNAVKY_0, :VIKENDDNES, :VIKENDOO, :MAX_POCET_OBJ_JIDEL;

  --EXCEPTION e_TEST ' **-*  '||cast(D_OBJEDNAVANI_  as cuvarchar50 )|| '  dnes '|| cast(VIKENDDNES AS CUVARCHAR20)|| '  obj '|| cast(VIKENDOO AS CUVARCHAR20);
  SELECT MOZNOST_BURZA_VLOZIT FROM TJIDELAK_JIDELNA WHERE LFD_JIDELNA = :LFD_JIDELNA_
    INTO MOZNOST_BURZA_VLOZIT_0;  
 
  :MOZNOST_OBJEDNAVAT = 'N';
  :MOZNOST_BURZA = 'N';

  -- NEDOVOLENÁ BURZA
  IF((DATUM_-D_OBJEDNAVANI_0 ) >= 0) THEN
  BEGIN
    IF ((VIKENDOO=VIKENDDNES )  ) THEN
    BEGIN
      IF((DATUM_-D_OBJEDNAVANI_0 ) > OBJEDNAVKY_PREDEM_DNI_0) THEN
      BEGIN
        :MOZNOST_OBJEDNAVAT = 'A';
      END
      ELSE
      IF((DATUM_-D_OBJEDNAVANI_0 ) = OBJEDNAVKY_PREDEM_DNI_0) THEN
      BEGIN
        --  zde ještě rozlišuje čas objednání
        IF (:T_OBJEDNAVANI_0 < :T_DO_OBJEDNAVKY_0) THEN
        BEGIN
          :MOZNOST_OBJEDNAVAT =  'A';
        END
        ELSE
        BEGIN
          :MOZNOST_OBJEDNAVAT = 'N';
        END
      END
      ELSE
      BEGIN
        :MOZNOST_OBJEDNAVAT = 'N';
        IF (:T_OBJEDNAVANI_0 > '20:00') THEN
        BEGIN
          :MOZNOST_OBJEDNAVAT =  'N';
        END
      END
    END
    ELSE
    IF ((VIKENDOO>VIKENDDNES )  ) THEN
    BEGIN
      IF((DATUM_-D_OBJEDNAVANI_0 ) > (OBJEDNAVKY_PREDEM_DNI_0+2)) THEN
      BEGIN
        :MOZNOST_OBJEDNAVAT = 'A';
      END
      ELSE
      IF((DATUM_-D_OBJEDNAVANI_0 ) = (OBJEDNAVKY_PREDEM_DNI_0+2)) THEN
      BEGIN
        --  zde ještě rozlišuje čas objednání
        IF (:T_OBJEDNAVANI_0 < :T_DO_OBJEDNAVKY_0) THEN
        BEGIN
          :MOZNOST_OBJEDNAVAT =  'A';
        END
        ELSE
        BEGIN
          :MOZNOST_OBJEDNAVAT = 'N';
        END
      END
      ELSE
      BEGIN
        :MOZNOST_OBJEDNAVAT = 'N';
      END
    END
  END    
  FOR SELECT JI.JIDELAK_NR,JI.DATUM, JI.LFD_NN, JI.SKLD_NR , S.SKLAD_NR 
    ,JI.CENA , JI.CENADPH --cena z jídeláku
    ,DECODE(:LFD_JAZYK_,1 ,IIF((SN.NAZEV_X IS NULL), S.NAZEV, SN.NAZEV_X)
                , 4 ,SN.NAZEV_E ) AS RETVAL
    --,S.NAZEV AS SKLD_NAZEV  
    --,SN.NAZEV_X , ,SN.NAZEV_R ,SN.NAZEV_D 
    ,SCA.CENADPH    --cena ze skladu
    FROM TJIDELAK JI  
    LEFT JOIN TSKLAD        S ON JI.SKLD_NR=S.SKLD_NR  
    LEFT JOIN TSKLAD_NAZEV SN ON JI.SKLD_NR=SN.SKLD_NR  
    LEFT JOIN TSKLAD_CENA SCA ON (SCA.SKLD_NR=JI.SKLD_NR) AND (SCA.LFD_DEA=1)
    WHERE (DATUM = :DATUM_)  AND (JI.OBJ_TERMINAL='A') 
          AND  (JI.LFD_JI_TYP = :LFD_JI_TYP_)
          AND  (JI.LFD_JI_TYP_CAST = :LFD_JI_TYP_CAST_)
          AND  (JI.LFD_NN) BETWEEN :JIDLO_OD_0 AND :JIDLO_DO_0

    ORDER BY DATUM, LFD_NN
    INTO  :JIDELAK_NR, :DATUM, :LFD_NN, :SKLD_NR, :SKLAD_NR ,:CENA , :CENADPH, :SKLD_NAZEV, :SKLD_CENADPH
    DO 
    BEGIN 
      :OBJEDNAVKA0 = 'N';
      :MAM_VBURZE = 'N';
      :JE_VBURZE = 'N';
      :VYDANO = 'N';
      :T_CAS0 = '0:00';
      IF (EXISTS (SELECT ZA_NR FROM TZA_JIDLA ZJ
        WHERE (ZJ.ZA_NR = :ZA_NR_) AND (DATUM = :DATUM_) AND (SKLD_NR=:SKLD_NR) -- AND (ZJ.JIDELAK_NR = :JIDELAK_NR) 
            )) THEN
      BEGIN       
        :OBJEDNAVKA0 = 'A';
        IF (:MOZNOST_OBJEDNAVAT = 'N') THEN
        BEGIN

        END   

        SELECT FIRST 1 POCET, T_CAS,BURZA, UZAVRENO FROM TZA_JIDLA ZJ
          WHERE (ZJ.ZA_NR = :ZA_NR_) AND (DATUM = :DATUM_) AND (SKLD_NR=:SKLD_NR)--AND (ZJ.JIDELAK_NR = :JIDELAK_NR) 
          into :POCET, :T_CAS0, :MAM_VBURZE ,:VYDANO; 

      END  
      execute procedure TSklad_ALERGENY_KUS(:SKLD_NR)
      RETURNING_VALUES(:ALG_CISLA_0, :ALG_NAZEV_0 );
      :JE_VBURZE = 'N';
      IF (:VYDANO = 'A') THEN
      BEGIN
          :MOZNOST_BURZA='N';
          :MOZNOST_BURZA_VLOZIT='N';
      END
      SUSPEND;
    END
  IF (LFD_JIDELNA_=201) THEN
  BEGIN
     --Teplé BAry, no stres na centrále, jídelna 201

    FOR SELECT 0,'TODAY', JI.PORADI, JI.SKLD_NR , S.SKLAD_NR 
      ,0 , 0 --cena z jídeláku
      ,DECODE(:LFD_JAZYK_,1 ,IIF((SN.NAZEV_X IS NULL), S.NAZEV, SN.NAZEV_X)
                  , 4 ,SN.NAZEV_E ) AS RETVAL
      ,SCA.CENADPH    --cena ze skladu
      FROM TPOKLADNA_KLAVESY JI
      LEFT JOIN TSKLAD        S ON JI.SKLD_NR=S.SKLD_NR  
      LEFT JOIN TSKLAD_NAZEV SN ON JI.SKLD_NR=SN.SKLD_NR  
      LEFT JOIN TSKLAD_CENA SCA ON (SCA.SKLD_NR=JI.SKLD_NR) AND (SCA.LFD_DEA=1)

      WHERE (JI.LFD_POK = 204) AND (JI.SKUPINA = '0009') AND (JI.PORADI IN (13,17,21) )

      ORDER BY JI.PORADI
      INTO  :JIDELAK_NR, :DATUM, :LFD_NN, :SKLD_NR, :SKLAD_NR ,:CENA , :CENADPH, :SKLD_NAZEV, :SKLD_CENADPH
      DO BEGIN
        IF (LFD_NN=13) THEN LFD_NN = 51;
        ELSE
        IF (LFD_NN=17) THEN LFD_NN = 52;
        ELSE
        IF (LFD_NN=21) THEN LFD_NN = 53;
        ELSE LFD_NN = 50;
        SUSPEND;
      END
  END

END